# -*- coding: utf-8 -*-
"""LeafClassification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1djaXXRnAJwtjezCgMTvV7oeVCFRmn3sG
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import torchvision
import torchvision.datasets as dset
import torchvision.transforms as transforms
from torch.utils.data import DataLoader, Dataset
import matplotlib.pyplot as plt
import torchvision.utils
import numpy as np
import random
from PIL import Image
import torch
from torch.autograd import Variable
import PIL.ImageOps
import torch.nn as nn
from torch import optim
import torch.nn.functional as F
import torchvision.models as models
import os
import random
from torch.optim import lr_scheduler
import json

print(os.getcwd())
# root_path = os.path.join(os.getcwd(), 'deep_learning_backend') # windows
root_path = "" # linux

plant_name = os.path.join(root_path, 'plants_name.json')
with open(plant_name) as plant_name_file:
    plant_names = json.load(plant_name_file)

def set_seed(seed):
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    np.random.seed(seed)
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)


set_seed(1)


def imshow(img, text=None, should_save=False):
    npimg = img.numpy()
    plt.axis("off")
    if text:
        plt.text(75,
                 8,
                 text,
                 style='italic',
                 fontweight='bold',
                 bbox={
                     'facecolor': 'white',
                     'alpha': 0.8,
                     'pad': 10
                 })
    plt.imshow(np.transpose(npimg, (1, 2, 0)))
    plt.show()

def build_network(model_name, pretrained=True):
  out_features = 112
  if model_name == "resnet18" or model_name == "resnet152":
    model = models.resnet18(pretrained) if model_name == "resnet18" else models.resnet152(pretrained)
    in_features = model.fc.in_features
    model.fc = nn.Linear(in_features, out_features)
    if not pretrained:
      for name, param in model.named_parameters():
        if not any(name.startswith(ext) for ext in ['layer3', 'layer4', 'fc']):
          param.requires_grad = False
  return model

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])

model_path = os.path.join(root_path, 'leaf_classifier_model.pth')
print(model_path)
if torch.cuda.is_available():
    net = build_network(model_name="resnet152", pretrained=True).cuda()
    net.load_state_dict(torch.load(model_path))
    net.eval()
else:
    net = build_network(model_name="resnet152", pretrained=True)
    net.load_state_dict(torch.load(model_path, map_location=torch.device('cpu')))
    net.eval()

def predict(img):
    img = transform(img)
    # imshow(img)
    if torch.cuda.is_available():
        img = img.unsqueeze(0).cuda()
    else:
        img = img.unsqueeze(0)
    out = net(img)
    probs = torch.softmax(out, dim=1)
    idx = probs.argmax(dim=1).item()
    
    return plant_names[idx]
